channels:
  - conda-forge
dependencies:
  - amostra
  - area-detector-handlers
  - arvpyf
  - atsas-pipelines
  - blosc
  - bokeh
  - boto3
  - bottleneck
  - chxtools
  - csxtools>=0.1.14
  - dask
  - dask-image
  - dask-jobqueue
  - dask-labextension
  - dask-ml
  - dask-xgboost
  - databroker>=2.0.0b8
  - eiger-io
  - fabio
  - graphviz
  - h5py>=3.6
  - hvplot
  - hxntools
  - ipympl
  - jupyterhub-singleuser=1.3.0  # match JupyterHub deployment version
  - jupyterlab=3.2.*
  - line_profiler
  - lixtools
  - lmfit>=0.9.9
  - matplotlib>=3.5
  - memory_profiler
  - mendeleev
  - modestimage
  - nbclassic>=0.2.8
  - nbgitpuller
  - nbserverproxy
    # - netcdf4  # jams up the solver, and unclear whether it is actually used
  - nodejs
  - notebook
  - nslsii
  - numba
  - numexpr
  - numpy>=1.22
  - pandas
  - papermill
  - periodictable
  - photutils
  - pip  # mamba warns us to explicitly list this dependency
  - py-xgboost
  - py4xs
  - pyarrow
  - pycentroids
  - pychx >=4.1.2
  - pyfai
  - pymongo
  - pypdf2
  - pystackreg
  - pytables
  - python-blosc
  - python-graphviz
  - python=3.9
  - pyxrf>=0.0.9
  - reportlab
  - requests
  - sasview
  - scikit-learn
  - scipy>=1.9
  - seaborn
  - shadow3
  - sip
  - sixtools>=0.0.2
  - srwpy
  - tiled>=0.1.0a70
  - tornado
  - tzlocal <3  # tzlocal 3 broke API on Python 3.7 and the fix turned into a rabbithole
  - voila
  - xarray
  - xray-vision >=0.0.10
  - xraylarch>=0.9.45
  - pip:
    - mimesis
    - pyzbar
    - smi_analysis
  
